### ISSUE TITLE
Site.objects.get_current() is not schema aware

### ISSUE THREAD

**Issue by honur** [bernardopires/django-tenant-schemas#261]
After django caches current site, Site.objects.get_current() returns wrong site for other sites.

**Comment by vinitkumar** [comment]
@honur Were you able to fix this issue?

**Comment by vinitkumar** [comment]
@bernardopires I would be happy to contribute a fix to this. Do you have any ideas in mind about the fix?

**Comment by honur** [comment]
Hi @vinitkumar 
Unfortunately I didn't have time to fix this issue, but I see a quick fix there. 
In middleware.py clear the sites cache as it is done for ContentType model, i.e. Site.objects.clear_cache()

**Comment by honur** [comment]
But ideally, it should be checked if 'django.contrib.sites' is in TENANT_APPS and then clear the cache. (And I guess it should be done for contenttypes too)

**Comment by bernardopires** [comment]
I don't understand why people are even using sites? This app should be a complete replacement to sites.

**Comment by vinitkumar** [comment]
@bernardopires I am using your app as a basic for creating a multi tenant CMS with django-cms. The thing is Django CMS uses Site in their top navbar to show which website it belongs to. Since, I have many tenants on the system with their websites, it is almost crucial to show them the context via sites. This apps works perfectly the way it is intended (to provide schema based multitenancy).

**Comment by vinitkumar** [comment]
@honur Thanks for your fix. I think that should do it.

**Comment by bernardopires** [comment]
Honestly I would customize django-cms to stop using sites, I think that makes more sense. Unfortunately I can't support every scenario so a patch for this would not be accepted. Thanks for reporting this though and hopefully it will be useful to more people.
