### ISSUE TITLE
Wrapped management command not working?

### ISSUE THREAD

**Issue by renegadeofunk** [bernardopires/django-tenant-schemas#302]
Hi bernardopires,

I'm using django-tenant-schemas 1.5.7 and everything has been working great except for one thing, I can't get createsuperuser to work with the schema flag. This is what I get:

(MSS) mbp:mss-portal jt $ ./manage.py createsuperuser --username='admin' --schema=a
usage: manage.py createsuperuser [-h] [--version] [-v {0,1,2,3}]
                                 [--settings SETTINGS]
                                 [--pythonpath PYTHONPATH] [--traceback]
                                 [--no-color] [--username USERNAME]
                                 [--noinput] [--database DATABASE]
                                 [--email EMAIL]
manage.py createsuperuser: error: unrecognized arguments: --schema=a

The migrate_schemas command works fine however. Any help is appreciated! Thank you.

**Comment by bernardopires** [comment]
I'm afraid you'll have to move Django 1.6. Note that 1.8 is already out!

**Comment by saqebakhter** [comment]
Having same issue.

**Comment by bkellgren** [comment]
Same here

**Comment by prokaktus** [comment]
For workaround you could try with `tenant_command`:
 ```
./manage.py tenant_command createsuperuser --username='admin' --schema=a
```

**Comment by bkellgren** [comment]
@prokaktus thanks this is what I ended up doing eventually and it worked

**Comment by bernardopires** [comment]
I've looked into this and the command is actually working, the problem is that the old one is being loaded. So on `settings.py` I believe a lot of people have the following line:

```INSTALLED_APPS = list(set(SHARED_APPS + TENANT_APPS))```

There are actually two problems here. So the official Django docs on overriding commands is 

> When several applications provide management commands with the same name, Django loads the command from the application that comes first in INSTALLED_APPS.

The problem with the line I posted above is that `set` is unordered and will ignore whichever order is in the object you passed. So there is no guarantee of in which position `tenant_schemas` will be.

An easy but relatively ugly fix is to use `OrderedDict.fromkeys` and to load `SHARED_APPS` first.

```
from collections import OrderedDict
INSTALLED_APPS = list(OrderedDict.fromkeys(SHARED_APPS + TENANT_APPS))
```

What do you guys think? Anyone else sees a better solution? @goodtune

**Comment by goodtune** [comment]
My preference is to populate INSTALLED_APPS without trying to be too join them. There could be valid use cases for mingling the order (template precedence, for example) that rules out concatenation.

We could use the checking framework to provide a warning/error if there are apps listed in either TENANT_APPS or SHARED_APPS that haven't been added to INSTALLED_APPS to protect users from leaving them out?

**Comment by goodtune** [comment]
I've got a branch where I'm doing this work, just having trouble getting the tests to pass... hopefully will have something tomorrow.
