### ISSUE TITLE
Alternative method to identify tenant

### ISSUE THREAD

**Issue by bliz937** [bernardopires/django-tenant-schemas#374]
Hi,

I would like to use this package but need to identify the tenant by a given string as apposed to using [the domain](https://github.com/bernardopires/django-tenant-schemas#how-it-works). 

Essentially what I would like to achieve is 

site.com/1 

as apposed to 

1.site.com

Would I be able to do this with django-tenant-schemas?

**Comment by goodtune** [comment]
It should be quite easily using the `utils` module.

https://django-tenant-schemas.readthedocs.io/en/latest/use.html#utils

```python
from tenant_schemas.utils import get_tenant_model, tenant_context
from myapp.models import Foo

def view(request, tenant_pk, foo_pk):
    Tenant = get_tenant_model()
    t = get_object_or_404(Tenant, pk=tenant_pk)
    with tenant_context(t):
        f = get_object_or_404(Foo, pk=foo_pk)
    # rest of your view
```

You might like to turn that pattern into a decorator that handles the getting of the tenant and setting the context to reduce boilerplate in your views.... that might even be a nice pull request to contribute back?

**Comment by bernardopires** [comment]
So basically you want to use subfolders for selecting tenants instead of subdomains. The file you want to change is https://github.com/bernardopires/django-tenant-schemas/blob/master/tenant_schemas/middleware.py

You can use `request.get_full_path()` to do what you want. You'll have to alter the request object as Django uses the path after the host name for matching which view to use.

**Comment by bernardopires** [comment]
Closing this for now, feel free to reopen!
