### ISSUE TITLE
What's the equivalent of sync_schemas in the new version?

### ISSUE THREAD

**Issue by danprado** [bernardopires/django-tenant-schemas#382]
I would like to call a "sync_schemas" command to apply some changes I have made to my "Shared vs Tenant apps". 
How can I do that in the new version?

**Comment by bernardopires** [comment]
Should be in the docs, didn't `migrate_schemas` work for you?

**Comment by DanPrado** [comment]
Oh, are they the same? I thought they had different behaviour.
I have moved a couple apps from Shared to Tenant and migrate_schemas shows "no migrations to apply".
Makemigrations shows "no changes detected" also.
I've found some old issues mentioning the "sync_schemas" command. That's why I thought it would have a different behaviour.
Do you have any suggestions on what I can try to force it to apply my changes to tenant apps?

**Comment by bernardopires** [comment]
Please just follow the manual and make sure you upgrade Django (if you are on a version older than 1.8). The docs don't even mention `sync_schemas` anymore, that was before Django 1.8. You should check the django docs regarding migrations. You are proably missing the initial migrations.

**Comment by DanPrado** [comment]
I'm using the latest version of Django.
I have the initial migrations and everything was working fine.
My issue is: after moving some apps from shared to tenant, "makemigrations" or "migrate_schames" doesn't apply any migrations.
Any tips?
