### ISSUE TITLE
post_shcema_sync doesn't work as expected

### ISSUE THREAD

**Issue by emostafa** [bernardopires/django-tenant-schemas#400]
Hello there,

i am playing with django-tenant-schemas, it's awesome so far, i have just this one issue.
in apps.py in one of my apps i have this:

```
class MyAppConfig(AppConfig):
     name = 'myapp'

     def ready(self):
         post_schema_sync(do_something, sender=MyTenantModel)
```

expected behaviour:
i am expecting "do_something" to be called after migrations of specific apps

current behaviour:
"do_something" never get called.

is this a bug, or there is something i am missing?

**Comment by AlexvEck** [comment]
Hi,

The post_schema_sync signal is sent when a tenant is new and if auto_create_schema is set to True.  In other words, it is sent when a tenant is created. For reference please check `tenant_schemas/models.py`

```
....
        if is_new and self.auto_create_schema:
            try:
                self.create_schema(check_if_exists=True, verbosity=verbosity)
            except:
                 ....
            else:
                post_schema_sync.send(sender=TenantMixin, tenant=self)
....
```

Also, the code sample you have provided does not attach the receiver function correctly. It should be `post_schema_sync.connect(do_something, sender=MyTenantModel)`. 

You expected behaviour sounds very familiar to the post_migrate signal provided by Django itself. [Is this what you are looking for?](https://docs.djangoproject.com/en/1.10/ref/signals/#post-migrate)

**Comment by emostafa** [comment]
thank you (Y)
