### ISSUE TITLE
Best Practices

### ISSUE THREAD

**Issue by Cosbgn** [bernardopires/django-tenant-schemas#418]
Hi, I have couple of question, if this is not the right place feel free to delete.
I'm new to Django and I'm trying to figure out what's the best practice to build a SAAS app. 

With the tenant schemas, will my app (for example a to-do) be in the Django admin for each user, or in the "front-end"?

Can the multi tenant schemas be implemented after I've developed my app? or I should set up these things before starting to code my app?

Thanks!

**Comment by AlexvEck** [comment]
Hi, indeed this is not the best place to post these kind of questions.

A better place would be [stackoverflow](https://stackoverflow.com) or [reddit.com/r/django](https://reddit.com/r/django).

But I'll answer your question anyway. ;)

It is advised to start with django-tenant-schemas right away, since migrating from a single tenant app to a multi-tenant app can be a pain.

The use case for this package is to separate data from different user groups in different schemas as opposed to have all data be in 1 table with foreign keys to which user group they belong to. Every user groups gets their own sub domain (for ex. group1.yourdomain.com and group2.yourdomain.com) and is called a tenant. django-tenant-schemas takes care of connecting group1 to the right database schema for that tenant. From a database perspective the groups are different databases.

Some data can be shared between tenants in a public schema, this is also where django-tenant-schemas stores which tenants exist and what their schemas are called. Every tenant can use data from the public schema, but no tenant can access another tenants schema.

Hope this gives you an overview, happy coding!
